package setauth

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/pedromvgomes/gt/internal/git"
	"github.com/pedromvgomes/gt/internal/ui"
)

type Result struct {
	Stdout string
	Stderr string
	Exit   int
}

type Runner interface {
	LookPath(file string) (string, error)
	Run(ctx context.Context, dir, name string, args ...string) (Result, error)
	Env(name string) string
	GOOS() string
}

type ExecRunner struct{}

func (ExecRunner) LookPath(file string) (string, error) {
	return exec.LookPath(file)
}

func (ExecRunner) Run(ctx context.Context, dir, name string, args ...string) (Result, error) {
	slog.Debug("running command", "dir", dir, "name", name, "args", args)
	cmd := exec.CommandContext(ctx, name, args...)
	if dir != "" {
		cmd.Dir = dir
	}
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	result := Result{Stdout: stdout.String(), Stderr: stderr.String()}
	if err == nil {
		return result, nil
	}
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		result.Exit = exitErr.ExitCode()
		return result, fmt.Errorf("%s %s failed with exit %d: %s", name, strings.Join(args, " "), result.Exit, strings.TrimSpace(result.Stderr))
	}
	return result, fmt.Errorf("run %s %s: %w", name, strings.Join(args, " "), err)
}

func (ExecRunner) Env(name string) string {
	return os.Getenv(name)
}

func (ExecRunner) GOOS() string {
	return runtime.GOOS
}

type Options struct {
	CWD  string
	User string
}

func Run(ctx context.Context, runner Runner, printer *ui.UI, opts Options) error {
	root, err := git.FindRepoRoot(opts.CWD)
	if err != nil {
		return err
	}
	if err := ensureDirenv(ctx, runner, printer); err != nil {
		return err
	}
	user, err := determineUser(ctx, runner, printer, opts.User)
	if err != nil {
		return err
	}
	expected, err := EnvrcContent(user)
	if err != nil {
		return err
	}
	envrcPath := filepath.Join(root, ".envrc")
	changed, err := writeEnvrc(printer, envrcPath, expected)
	if err != nil {
		return err
	}
	if changed {
		printer.Success("Updated %s", envrcPath)
	} else {
		printer.Info("%s is already up to date", envrcPath)
	}
	if _, err := runner.Run(ctx, "", "direnv", "allow", root); err != nil {
		return err
	}
	smokeTestHook(ctx, runner, printer, root)
	return nil
}

func EnvrcContent(user string) (string, error) {
	user = strings.TrimSpace(user)
	if !validGitHubUser(user) {
		return "", ui.Errorf(ui.ExitUser, "invalid GitHub user %q", user)
	}
	return fmt.Sprintf(`# Auto-generated by gt set-auth.
# Scopes GH_TOKEN to gh user '%[1]s' so 'gh pr create' etc.
# authenticate as %[1]s regardless of 'gh auth switch'.
export GH_TOKEN="$(gh auth token --user %[1]s)"
`, user), nil
}

func ensureDirenv(ctx context.Context, runner Runner, printer *ui.UI) error {
	if _, err := runner.LookPath("direnv"); err == nil {
		return nil
	}
	switch runner.GOOS() {
	case "darwin":
		answer, err := printer.Prompt("Install direnv via 'brew install direnv'? [Y/n]", "Y", false, "")
		if err != nil {
			return err
		}
		if !isYes(answer) {
			return ui.Errorf(ui.ExitGeneral, "direnv is required; install it with 'brew install direnv'")
		}
		if _, err := runner.Run(ctx, "", "brew", "install", "direnv"); err != nil {
			return err
		}
		return nil
	case "linux":
		return ui.Errorf(ui.ExitGeneral, "direnv is required; install it from https://direnv.net/docs/installation.html")
	default:
		return ui.Errorf(ui.ExitGeneral, "direnv is required; install it from https://direnv.net/docs/installation.html")
	}
}

func determineUser(ctx context.Context, runner Runner, printer *ui.UI, explicit string) (string, error) {
	if strings.TrimSpace(explicit) != "" {
		if !validGitHubUser(explicit) {
			return "", ui.Errorf(ui.ExitUser, "invalid GitHub user %q", explicit)
		}
		return strings.TrimSpace(explicit), nil
	}
	result, err := runner.Run(ctx, "", "gh", "api", "user", "--jq", ".login")
	if err != nil {
		return "", err
	}
	def := strings.TrimSpace(result.Stdout)
	answer, err := printer.Prompt("GH_TOKEN should authenticate as which user?", def, true, "set --user to skip the prompt")
	if err != nil {
		return "", err
	}
	answer = strings.TrimSpace(answer)
	if answer == "" {
		return "", ui.Errorf(ui.ExitUser, "GitHub user is required")
	}
	if !validGitHubUser(answer) {
		return "", ui.Errorf(ui.ExitUser, "invalid GitHub user %q", answer)
	}
	return answer, nil
}

func writeEnvrc(printer *ui.UI, path, expected string) (bool, error) {
	current, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return false, fmt.Errorf("read .envrc: %w", err)
		}
		if err := os.WriteFile(path, []byte(expected), 0o644); err != nil {
			return false, fmt.Errorf("write .envrc: %w", err)
		}
		return true, nil
	}
	if string(current) == expected {
		return false, nil
	}
	_, _ = fmt.Fprintf(printer.Err, "Existing .envrc differs:\n%s", DiffEnvrc(string(current), expected))
	answer, err := printer.Prompt("Overwrite? [y/N]", "N", false, "")
	if err != nil {
		return false, err
	}
	if !isYes(answer) {
		return false, ui.Errorf(ui.ExitGeneral, ".envrc differs; not overwriting")
	}
	if err := os.WriteFile(path, []byte(expected), 0o644); err != nil {
		return false, fmt.Errorf("write .envrc: %w", err)
	}
	return true, nil
}

func DiffEnvrc(current, expected string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimSuffix(current, "\n"), "\n") {
		_, _ = fmt.Fprintf(&b, "- %s\n", line)
	}
	for _, line := range strings.Split(strings.TrimSuffix(expected, "\n"), "\n") {
		_, _ = fmt.Fprintf(&b, "+ %s\n", line)
	}
	return b.String()
}

func smokeTestHook(ctx context.Context, runner Runner, printer *ui.UI, root string) {
	shell := runner.Env("SHELL")
	if shell == "" {
		shell = "sh"
	}
	if _, err := runner.Run(ctx, "", shell, "-lc", "cd "+shellQuote(root)+" && test -n \"${DIRENV_DIR:-}\""); err == nil {
		return
	}
	printer.Warn("direnv is allowed for this repository, but your shell hook may be missing.")
	if hook := hookInstruction(filepath.Base(shell)); hook != "" {
		printer.Warn("Add this to your shell rc file: %s", hook)
	}
}

func hookInstruction(shell string) string {
	switch shell {
	case "zsh":
		return `eval "$(direnv hook zsh)"`
	case "bash":
		return `eval "$(direnv hook bash)"`
	case "fish":
		return "direnv hook fish | source"
	default:
		return ""
	}
}

func validGitHubUser(user string) bool {
	user = strings.TrimSpace(user)
	if user == "" || len(user) > 39 || strings.HasPrefix(user, "-") || strings.HasSuffix(user, "-") {
		return false
	}
	for _, r := range user {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-' {
			continue
		}
		return false
	}
	return true
}

func isYes(answer string) bool {
	answer = strings.ToLower(strings.TrimSpace(answer))
	return answer == "" || answer == "y" || answer == "yes"
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
