package setauth

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"

	"github.com/pedromvgomes/gt/internal/config"
	"github.com/pedromvgomes/gt/internal/git"
	"github.com/pedromvgomes/gt/internal/ui"
)

type Result struct {
	Stdout string
	Stderr string
	Exit   int
}

type Runner interface {
	LookPath(file string) (string, error)
	Run(ctx context.Context, dir, name string, args ...string) (Result, error)
	Env(name string) string
	GOOS() string
}

type ExecRunner struct{}

func (ExecRunner) LookPath(file string) (string, error) {
	return exec.LookPath(file)
}

func (ExecRunner) Run(ctx context.Context, dir, name string, args ...string) (Result, error) {
	slog.Debug("running command", "dir", dir, "name", name, "args", args)
	// `name` is variable, but never from user input: every caller passes a
	// literal — direnv, brew, gh, or the login shell from $SHELL. argv goes
	// through as a slice, so no shell splits it.
	// #nosec G204 -- callers pass literal binary names; argv is not shell-parsed.
	// nosemgrep: go.lang.security.audit.dangerous-exec-command.dangerous-exec-command
	cmd := exec.CommandContext(ctx, name, args...)
	if dir != "" {
		cmd.Dir = dir
	}
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	result := Result{Stdout: stdout.String(), Stderr: stderr.String()}
	if err == nil {
		return result, nil
	}
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		result.Exit = exitErr.ExitCode()
		return result, fmt.Errorf("%s %s failed with exit %d: %s", name, strings.Join(args, " "), result.Exit, strings.TrimSpace(result.Stderr))
	}
	return result, fmt.Errorf("run %s %s: %w", name, strings.Join(args, " "), err)
}

func (ExecRunner) Env(name string) string {
	return os.Getenv(name)
}

func (ExecRunner) GOOS() string {
	return runtime.GOOS
}

type Options struct {
	CWD  string
	User string

	// Profiles is the configured profile list; RepoURL is what its match
	// patterns are tested against. When RepoURL is empty, Run reads the origin
	// remote, which is what lets an already-cloned repository be retrofitted
	// with a bare 'gt set-auth'.
	Profiles  []config.Profile
	RepoURL   string
	Profile   string
	NoProfile bool

	// Yes skips the confirmation before overwriting an .envrc that differs, so
	// a sweep over existing clones can run unattended.
	Yes bool
}

func Run(ctx context.Context, runner Runner, printer *ui.UI, opts Options) error {
	root, err := git.FindRepoRoot(opts.CWD)
	if err != nil {
		return err
	}
	if err := ensureDirenv(ctx, runner, printer); err != nil {
		return err
	}
	envrcPath := filepath.Join(root, ".envrc")
	current, hasCurrent, err := readEnvrc(envrcPath)
	if err != nil {
		return err
	}
	user, err := determineUser(ctx, runner, printer, opts.User, current)
	if err != nil {
		return err
	}
	repoURL := opts.RepoURL
	if repoURL == "" && needsRepoURL(opts) {
		repoURL = originURL(ctx, runner, root)
	}
	profile, err := ResolveProfile(opts.Profiles, repoURL, opts.Profile, opts.NoProfile)
	if err != nil {
		return err
	}
	expected, err := EnvrcContent(user, profile)
	if err != nil {
		return err
	}
	changed, err := writeEnvrc(printer, envrcPath, current, hasCurrent, expected, opts.Yes)
	if err != nil {
		return err
	}
	if changed {
		if !profile.Empty() {
			printer.Info("Applied profile %q (%s)", profile.Name, strings.Join(profile.Names(), ", "))
		}
		printer.Success("Updated %s", envrcPath)
	} else {
		printer.Info("%s is already up to date", envrcPath)
	}
	if _, err := runner.Run(ctx, "", "direnv", "allow", root); err != nil {
		return err
	}
	smokeTestHook(ctx, runner, printer, root)
	return nil
}

// EnvrcContent renders the managed .envrc. An empty profile renders exactly
// what gt emitted before profiles existed, so a repository that has not opted
// in is never rewritten.
func EnvrcContent(user string, profile Profile) (string, error) {
	user = strings.TrimSpace(user)
	if !validGitHubUser(user) {
		return "", ui.Errorf(ui.ExitUser, "invalid GitHub user %q", user)
	}
	var b strings.Builder
	_, _ = fmt.Fprintf(&b, `# Auto-generated by gt set-auth.
# Scopes GH_TOKEN to gh user '%[1]s' so 'gh pr create' etc.
# authenticate as %[1]s regardless of 'gh auth switch'.
export GH_TOKEN="$(gh auth token --user %[1]s)"
`, user)
	if profile.Empty() {
		return b.String(), nil
	}
	_, _ = fmt.Fprintf(&b, `
# Profile '%s' from the gt config. Pins the environment that tooling launched
# from this checkout resolves, so it does not depend on the shell it started in.
`, profile.Name)
	for _, v := range profile.Env {
		_, _ = fmt.Fprintf(&b, "export %s=%s\n", v.Name, shellDoubleQuote(v.Value))
	}
	return b.String(), nil
}

// needsRepoURL keeps set-auth from shelling out to git when nothing would be
// matched against the URL anyway: no configured profiles, or a selection that
// is already decided by a flag.
func needsRepoURL(opts Options) bool {
	return len(opts.Profiles) > 0 && !opts.NoProfile && strings.TrimSpace(opts.Profile) == ""
}

// originURL is best-effort: a repository with no origin simply matches no
// profile, which is the same outcome as not opting in.
func originURL(ctx context.Context, runner Runner, root string) string {
	result, err := runner.Run(ctx, root, "git", "remote", "get-url", "origin")
	if err != nil {
		return ""
	}
	return strings.TrimSpace(result.Stdout)
}

func ensureDirenv(ctx context.Context, runner Runner, printer *ui.UI) error {
	if _, err := runner.LookPath("direnv"); err == nil {
		return nil
	}
	switch runner.GOOS() {
	case "darwin":
		answer, err := printer.Prompt("Install direnv via 'brew install direnv'? [Y/n]", "Y", false, "")
		if err != nil {
			return err
		}
		if !isYes(answer) {
			return ui.Errorf(ui.ExitGeneral, "direnv is required; install it with 'brew install direnv'")
		}
		if _, err := runner.Run(ctx, "", "brew", "install", "direnv"); err != nil {
			return err
		}
		return nil
	case "linux":
		return ui.Errorf(ui.ExitGeneral, "direnv is required; install it from https://direnv.net/docs/installation.html")
	default:
		return ui.Errorf(ui.ExitGeneral, "direnv is required; install it from https://direnv.net/docs/installation.html")
	}
}

func determineUser(ctx context.Context, runner Runner, printer *ui.UI, explicit, current string) (string, error) {
	if strings.TrimSpace(explicit) != "" {
		if !validGitHubUser(explicit) {
			return "", ui.Errorf(ui.ExitUser, "invalid GitHub user %q", explicit)
		}
		return strings.TrimSpace(explicit), nil
	}
	// A managed .envrc already records the answer. Reusing it means re-running
	// set-auth to pick up a profile keeps the identity the repository was
	// cloned with, needs no flag, and does not have to ask.
	if user := userFromEnvrc(current); user != "" {
		return user, nil
	}
	result, err := runner.Run(ctx, "", "gh", "api", "user", "--jq", ".login")
	if err != nil {
		return "", err
	}
	def := strings.TrimSpace(result.Stdout)
	answer, err := printer.Prompt("GH_TOKEN should authenticate as which user?", def, true, "set --user to skip the prompt")
	if err != nil {
		return "", err
	}
	answer = strings.TrimSpace(answer)
	if answer == "" {
		return "", ui.Errorf(ui.ExitUser, "GitHub user is required")
	}
	if !validGitHubUser(answer) {
		return "", ui.Errorf(ui.ExitUser, "invalid GitHub user %q", answer)
	}
	return answer, nil
}

func readEnvrc(path string) (string, bool, error) {
	// #nosec G304 -- reads the .envrc gt manages, to compare before overwriting.
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, fmt.Errorf("read .envrc: %w", err)
	}
	return string(data), true, nil
}

func writeEnvrc(printer *ui.UI, path, current string, hasCurrent bool, expected string, yes bool) (bool, error) {
	// 0600: .envrc is direnv input evaluated as this user and nobody else.
	// It holds no token today — GH_TOKEN is a `gh auth token` call resolved
	// at load time — but it is the file that decides which GitHub identity a
	// checkout authenticates as, and that is not other users' business.
	if !hasCurrent {
		if err := os.WriteFile(path, []byte(expected), 0o600); err != nil {
			return false, fmt.Errorf("write .envrc: %w", err)
		}
		return true, nil
	}
	if current == expected {
		return false, nil
	}
	_, _ = fmt.Fprintf(printer.Err, "Existing .envrc differs:\n%s", DiffEnvrc(current, expected))
	if !yes {
		answer, err := printer.Prompt("Overwrite? [y/N]", "N", false, "")
		if err != nil {
			return false, err
		}
		if !isYes(answer) {
			return false, ui.Errorf(ui.ExitGeneral, ".envrc differs; not overwriting")
		}
	}
	if err := os.WriteFile(path, []byte(expected), 0o600); err != nil {
		return false, fmt.Errorf("write .envrc: %w", err)
	}
	return true, nil
}

// userFromEnvrc recovers the gh user from an .envrc gt previously wrote. It
// matches only gt's own generated line, so a hand-written .envrc yields
// nothing and the normal detection runs.
var envrcUserPattern = regexp.MustCompile(`export GH_TOKEN="\$\(gh auth token --user ([A-Za-z0-9-]+)\)"`)

func userFromEnvrc(current string) string {
	match := envrcUserPattern.FindStringSubmatch(current)
	if match == nil {
		return ""
	}
	if !validGitHubUser(match[1]) {
		return ""
	}
	return match[1]
}

func DiffEnvrc(current, expected string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimSuffix(current, "\n"), "\n") {
		_, _ = fmt.Fprintf(&b, "- %s\n", line)
	}
	for _, line := range strings.Split(strings.TrimSuffix(expected, "\n"), "\n") {
		_, _ = fmt.Fprintf(&b, "+ %s\n", line)
	}
	return b.String()
}

func smokeTestHook(ctx context.Context, runner Runner, printer *ui.UI, root string) {
	shell := runner.Env("SHELL")
	if shell == "" {
		shell = "sh"
	}
	if _, err := runner.Run(ctx, "", shell, "-lc", "cd "+shellQuote(root)+" && test -n \"${DIRENV_DIR:-}\""); err == nil {
		return
	}
	printer.Warn("direnv is allowed for this repository, but your shell hook may be missing.")
	if hook := hookInstruction(filepath.Base(shell)); hook != "" {
		printer.Warn("Add this to your shell rc file: %s", hook)
	}
}

func hookInstruction(shell string) string {
	switch shell {
	case "zsh":
		return `eval "$(direnv hook zsh)"`
	case "bash":
		return `eval "$(direnv hook bash)"`
	case "fish":
		return "direnv hook fish | source"
	default:
		return ""
	}
}

func validGitHubUser(user string) bool {
	user = strings.TrimSpace(user)
	if user == "" || len(user) > 39 || strings.HasPrefix(user, "-") || strings.HasSuffix(user, "-") {
		return false
	}
	for _, r := range user {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-' {
			continue
		}
		return false
	}
	return true
}

func isYes(answer string) bool {
	answer = strings.ToLower(strings.TrimSpace(answer))
	return answer == "" || answer == "y" || answer == "yes"
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
