version: 2

project_name: gt

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/gt
    binary: gt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      gt_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: git
