package tests

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/pedromvgomes/gt/internal/config"
	"github.com/pedromvgomes/gt/internal/setauth"
	"github.com/pedromvgomes/gt/internal/ui"
)

// baseEnvrc is the exact content gt emitted before profiles existed. Every
// repository that has not opted in must keep producing these bytes, or the
// next set-auth run rewrites every existing clone.
const baseEnvrc = `# Auto-generated by gt set-auth.
# Scopes GH_TOKEN to gh user 'pedromvgomes' so 'gh pr create' etc.
# authenticate as pedromvgomes regardless of 'gh auth switch'.
export GH_TOKEN="$(gh auth token --user pedromvgomes)"
`

func TestEnvrcContentWithoutProfileIsUnchanged(t *testing.T) {
	got, err := setauth.EnvrcContent("pedromvgomes", setauth.Profile{})
	if err != nil {
		t.Fatalf("EnvrcContent() error = %v", err)
	}
	if got != baseEnvrc {
		t.Fatalf("EnvrcContent() = %q, want %q", got, baseEnvrc)
	}
}

// A profile that resolved to no variables is the same case as no profile at
// all: a name alone must not perturb the file.
func TestEnvrcContentWithNamedButEmptyProfileIsUnchanged(t *testing.T) {
	got, err := setauth.EnvrcContent("pedromvgomes", setauth.Profile{Name: "personal"})
	if err != nil {
		t.Fatalf("EnvrcContent() error = %v", err)
	}
	if got != baseEnvrc {
		t.Fatalf("EnvrcContent() = %q, want %q", got, baseEnvrc)
	}
}

func TestEnvrcContentWithProfile(t *testing.T) {
	profile := setauth.Profile{Name: "personal", Env: []setauth.EnvVar{
		{Name: "CLAUDE_CONFIG_DIR", Value: "/home/p/.claude-personal"},
		{Name: "CODEX_HOME", Value: "/home/p/.codex"},
	}}
	got, err := setauth.EnvrcContent("pedromvgomes", profile)
	if err != nil {
		t.Fatalf("EnvrcContent() error = %v", err)
	}
	want := baseEnvrc + `
# Profile 'personal' from the gt config. Pins the environment that tooling launched
# from this checkout resolves, so it does not depend on the shell it started in.
export CLAUDE_CONFIG_DIR="/home/p/.claude-personal"
export CODEX_HOME="/home/p/.codex"
`
	if got != want {
		t.Fatalf("EnvrcContent() = %q, want %q", got, want)
	}
}

// Profile values are arbitrary strings interpolated into export VAR="...", so
// the characters the shell still reads inside double quotes are escaped.
func TestEnvrcContentEscapesProfileValues(t *testing.T) {
	profile := setauth.Profile{Name: "odd", Env: []setauth.EnvVar{
		{Name: "TRICKY", Value: "a\"b$c`d\\e"},
	}}
	got, err := setauth.EnvrcContent("pedromvgomes", profile)
	if err != nil {
		t.Fatalf("EnvrcContent() error = %v", err)
	}
	want := "export TRICKY=\"a\\\"b\\$c\\`d\\\\e\"\n"
	if !strings.Contains(got, want) {
		t.Fatalf("EnvrcContent() = %q, missing %q", got, want)
	}
}

func TestEnvrcContentRejectsInvalidUser(t *testing.T) {
	if _, err := setauth.EnvrcContent("bad user", setauth.Profile{}); err == nil {
		t.Fatal("EnvrcContent() succeeded, want error")
	}
}

func TestDiffEnvrcShowsCurrentAndExpectedLines(t *testing.T) {
	got := setauth.DiffEnvrc("export OLD=1\n", "export NEW=1\n")
	for _, want := range []string{"- export OLD=1", "+ export NEW=1"} {
		if !strings.Contains(got, want) {
			t.Fatalf("DiffEnvrc() = %q, missing %q", got, want)
		}
	}
}

func TestRunWritesEnvrcAndAllowsDirenv(t *testing.T) {
	root := makeManagedRoot(t)
	runner := &fakeCommandRunner{
		paths: map[string]bool{"direnv": true},
		env:   map[string]string{"SHELL": "bash"},
	}
	printer := quietUI()

	err := setauth.Run(context.Background(), runner, printer, setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, ".envrc"))
	if err != nil {
		t.Fatalf("read .envrc: %v", err)
	}
	if !strings.Contains(string(data), "gh auth token --user pedromvgomes") {
		t.Fatalf(".envrc = %q", string(data))
	}
	wantPrefix := [][]string{{"direnv", "allow", root}}
	if !reflect.DeepEqual(runner.calls[:1], wantPrefix) {
		t.Fatalf("call prefix = %#v, want %#v", runner.calls[:1], wantPrefix)
	}
}

func TestRunPromptsBeforeOverwritingEnvrc(t *testing.T) {
	root := makeManagedRoot(t)
	if err := os.WriteFile(filepath.Join(root, ".envrc"), []byte("export OLD=1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runner := &fakeCommandRunner{paths: map[string]bool{"direnv": true}}
	printer := &ui.UI{In: strings.NewReader("y\n"), Out: ioDiscard{}, Err: ioDiscard{}, Interactive: true}

	err := setauth.Run(context.Background(), runner, printer, setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".envrc"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "OLD") {
		t.Fatalf(".envrc was not overwritten: %q", string(data))
	}
}

func TestRunInstallsDirenvOnMacOSWhenAccepted(t *testing.T) {
	root := makeManagedRoot(t)
	runner := &fakeCommandRunner{goos: "darwin"}
	printer := &ui.UI{In: strings.NewReader("\n"), Out: ioDiscard{}, Err: ioDiscard{}, Interactive: true}

	err := setauth.Run(context.Background(), runner, printer, setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !runner.hasCall("brew install direnv") {
		t.Fatalf("calls = %#v, missing brew install", runner.calls)
	}
}

func TestRunErrorsWhenDirenvMissingOnLinux(t *testing.T) {
	root := makeManagedRoot(t)
	runner := &fakeCommandRunner{goos: "linux"}
	err := setauth.Run(context.Background(), runner, quietUI(), setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err == nil {
		t.Fatal("Run() succeeded, want error")
	}
	if !strings.Contains(err.Error(), "direnv.net") {
		t.Fatalf("Run() error = %v, want installation URL", err)
	}
}

type setauthResult struct {
	stdout string
	stderr string
	exit   int
	err    error
}

type fakeCommandRunner struct {
	calls     [][]string
	paths     map[string]bool
	responses map[string]setauthResult
	env       map[string]string
	goos      string
}

func (f *fakeCommandRunner) LookPath(file string) (string, error) {
	if f.paths[file] {
		return "/usr/bin/" + file, nil
	}
	return "", errors.New("not found")
}

func (f *fakeCommandRunner) Run(_ context.Context, _ string, name string, args ...string) (setauth.Result, error) {
	call := append([]string{name}, args...)
	f.calls = append(f.calls, call)
	key := strings.Join(call, " ")
	if result, ok := f.responses[key]; ok {
		return setauth.Result{Stdout: result.stdout, Stderr: result.stderr, Exit: result.exit}, result.err
	}
	return setauth.Result{}, nil
}

func (f *fakeCommandRunner) Env(name string) string {
	return f.env[name]
}

func (f *fakeCommandRunner) GOOS() string {
	if f.goos != "" {
		return f.goos
	}
	return "linux"
}

func (f *fakeCommandRunner) hasCall(want string) bool {
	for _, call := range f.calls {
		if strings.Join(call, " ") == want {
			return true
		}
	}
	return false
}

func TestResolveProfileMatchesRepoURLInOrder(t *testing.T) {
	profiles := []config.Profile{
		{Name: "work", Match: []string{"github.com:acme/*"}, Env: map[string]string{"CLAUDE_CONFIG_DIR": "/w"}},
		{Name: "catch-all", Match: []string{"*"}, Env: map[string]string{"CLAUDE_CONFIG_DIR": "/c"}},
	}
	cases := map[string]struct {
		url  string
		want string
	}{
		"first match wins":            {"git@github.com:acme/thing.git", "work"},
		"falls through to catch-all":  {"git@github.com:other/thing.git", "catch-all"},
		"no origin matches catch-all": {"", "catch-all"},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got, err := setauth.ResolveProfile(profiles, tc.url, "", false)
			if err != nil {
				t.Fatalf("ResolveProfile() error = %v", err)
			}
			if got.Name != tc.want {
				t.Fatalf("ResolveProfile() = %q, want %q", got.Name, tc.want)
			}
		})
	}
}

// A profile with no match patterns is inert: it exists only to be named.
func TestResolveProfileIgnoresUnmatchedProfiles(t *testing.T) {
	profiles := []config.Profile{
		{Name: "personal", Env: map[string]string{"CODEX_HOME": "/p"}},
	}
	got, err := setauth.ResolveProfile(profiles, "git@github.com:acme/thing.git", "", false)
	if err != nil {
		t.Fatalf("ResolveProfile() error = %v", err)
	}
	if !got.Empty() {
		t.Fatalf("ResolveProfile() = %#v, want empty", got)
	}
	got, err = setauth.ResolveProfile(profiles, "", "personal", false)
	if err != nil {
		t.Fatalf("ResolveProfile() error = %v", err)
	}
	if got.Name != "personal" || len(got.Env) != 1 {
		t.Fatalf("ResolveProfile() = %#v, want the named profile", got)
	}
}

func TestResolveProfileOptOuts(t *testing.T) {
	profiles := []config.Profile{
		{Name: "work", Match: []string{"*"}, Env: map[string]string{"CLAUDE_CONFIG_DIR": "/w"}},
	}
	for name, explicit := range map[string]string{"reserved name": "none", "flag": ""} {
		t.Run(name, func(t *testing.T) {
			got, err := setauth.ResolveProfile(profiles, "git@github.com:acme/t.git", explicit, explicit == "")
			if err != nil {
				t.Fatalf("ResolveProfile() error = %v", err)
			}
			if !got.Empty() {
				t.Fatalf("ResolveProfile() = %#v, want empty", got)
			}
		})
	}
}

func TestResolveProfileRejectsUnknownName(t *testing.T) {
	_, err := setauth.ResolveProfile(nil, "", "nope", false)
	if err == nil {
		t.Fatal("ResolveProfile() succeeded, want error")
	}
	if !strings.Contains(err.Error(), "nope") {
		t.Fatalf("ResolveProfile() error = %v, want the profile name", err)
	}
}

func TestResolveProfileExpandsHomeAndSortsVariables(t *testing.T) {
	home, err := os.UserHomeDir()
	if err != nil {
		t.Skip("no home directory")
	}
	profiles := []config.Profile{{Name: "p", Match: []string{"*"}, Env: map[string]string{
		"ZED_HOME":          "~",
		"CODEX_HOME":        "$HOME/.codex",
		"CLAUDE_CONFIG_DIR": "~/.claude-personal",
		"OPAQUE":            "not-a-path",
	}}}
	got, err := setauth.ResolveProfile(profiles, "any", "", false)
	if err != nil {
		t.Fatalf("ResolveProfile() error = %v", err)
	}
	want := []setauth.EnvVar{
		{Name: "CLAUDE_CONFIG_DIR", Value: filepath.Join(home, ".claude-personal")},
		{Name: "CODEX_HOME", Value: filepath.Join(home, ".codex")},
		{Name: "OPAQUE", Value: "not-a-path"},
		{Name: "ZED_HOME", Value: home},
	}
	if !reflect.DeepEqual(got.Env, want) {
		t.Fatalf("ResolveProfile().Env = %#v, want %#v", got.Env, want)
	}
}

// Retrofitting an existing clone: 'gt set-auth' with no --user recovers the
// identity from the .envrc gt already wrote, so it needs no flags and asks
// nothing, and a second run is a no-op.
func TestRunRetrofitsExistingEnvrcWithoutAskingForUser(t *testing.T) {
	root := makeManagedRoot(t)
	envrcPath := filepath.Join(root, ".envrc")
	if err := os.WriteFile(envrcPath, []byte(baseEnvrc), 0o600); err != nil {
		t.Fatal(err)
	}
	opts := setauth.Options{
		CWD:      root,
		Profiles: []config.Profile{{Name: "personal", Match: []string{"*"}, Env: map[string]string{"CODEX_HOME": "/p/.codex"}}},
		Yes:      true,
	}
	newRunner := func() *fakeCommandRunner {
		return &fakeCommandRunner{
			paths: map[string]bool{"direnv": true},
			responses: map[string]setauthResult{
				"git remote get-url origin": {stdout: "git@github.com:acme/thing.git\n"},
			},
		}
	}

	runner := newRunner()
	// Non-interactive: a prompt here would be an error, which is the point.
	if err := setauth.Run(context.Background(), runner, quietUI(), opts); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if runner.hasCall("gh api user --jq .login") {
		t.Fatalf("calls = %#v, want no gh lookup", runner.calls)
	}
	data, err := os.ReadFile(envrcPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), `export CODEX_HOME="/p/.codex"`) {
		t.Fatalf(".envrc = %q", string(data))
	}
	if !strings.Contains(string(data), "gh auth token --user pedromvgomes") {
		t.Fatalf(".envrc lost the gh user: %q", string(data))
	}

	// Idempotence: the second run changes nothing and reports it.
	before := string(data)
	out := &strings.Builder{}
	printer := &ui.UI{In: strings.NewReader(""), Out: out, Err: ioDiscard{}}
	if err := setauth.Run(context.Background(), newRunner(), printer, opts); err != nil {
		t.Fatalf("second Run() error = %v", err)
	}
	after, err := os.ReadFile(envrcPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != before {
		t.Fatalf("second run rewrote .envrc:\n%q\n%q", before, string(after))
	}
	if !strings.Contains(out.String(), "already up to date") {
		t.Fatalf("second run output = %q, want 'already up to date'", out.String())
	}
}

// A repository that matches nothing must keep the exact bytes it has, so
// running set-auth across every existing clone rewrites none of them.
func TestRunLeavesNonOptedInEnvrcByteIdentical(t *testing.T) {
	root := makeManagedRoot(t)
	envrcPath := filepath.Join(root, ".envrc")
	if err := os.WriteFile(envrcPath, []byte(baseEnvrc), 0o600); err != nil {
		t.Fatal(err)
	}
	runner := &fakeCommandRunner{
		paths: map[string]bool{"direnv": true},
		responses: map[string]setauthResult{
			"git remote get-url origin": {stdout: "git@github.com:other/thing.git\n"},
		},
	}
	err := setauth.Run(context.Background(), runner, quietUI(), setauth.Options{
		CWD:      root,
		Profiles: []config.Profile{{Name: "work", Match: []string{"github.com:acme/*"}, Env: map[string]string{"CODEX_HOME": "/w"}}},
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	data, err := os.ReadFile(envrcPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != baseEnvrc {
		t.Fatalf(".envrc = %q, want it untouched", string(data))
	}
}
