package tests

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/pedromvgomes/gt/internal/setauth"
	"github.com/pedromvgomes/gt/internal/ui"
)

func TestEnvrcContent(t *testing.T) {
	got, err := setauth.EnvrcContent("pedromvgomes")
	if err != nil {
		t.Fatalf("EnvrcContent() error = %v", err)
	}
	for _, want := range []string{
		"# Auto-generated by gt set-auth.",
		"export GH_TOKEN=\"$(gh auth token --user pedromvgomes)\"",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("EnvrcContent() = %q, missing %q", got, want)
		}
	}
}

func TestEnvrcContentRejectsInvalidUser(t *testing.T) {
	if _, err := setauth.EnvrcContent("bad user"); err == nil {
		t.Fatal("EnvrcContent() succeeded, want error")
	}
}

func TestDiffEnvrcShowsCurrentAndExpectedLines(t *testing.T) {
	got := setauth.DiffEnvrc("export OLD=1\n", "export NEW=1\n")
	for _, want := range []string{"- export OLD=1", "+ export NEW=1"} {
		if !strings.Contains(got, want) {
			t.Fatalf("DiffEnvrc() = %q, missing %q", got, want)
		}
	}
}

func TestRunWritesEnvrcAndAllowsDirenv(t *testing.T) {
	root := makeManagedRoot(t)
	runner := &fakeCommandRunner{
		paths: map[string]bool{"direnv": true},
		env:   map[string]string{"SHELL": "bash"},
	}
	printer := quietUI()

	err := setauth.Run(context.Background(), runner, printer, setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, ".envrc"))
	if err != nil {
		t.Fatalf("read .envrc: %v", err)
	}
	if !strings.Contains(string(data), "gh auth token --user pedromvgomes") {
		t.Fatalf(".envrc = %q", string(data))
	}
	wantPrefix := [][]string{{"direnv", "allow", root}}
	if !reflect.DeepEqual(runner.calls[:1], wantPrefix) {
		t.Fatalf("call prefix = %#v, want %#v", runner.calls[:1], wantPrefix)
	}
}

func TestRunPromptsBeforeOverwritingEnvrc(t *testing.T) {
	root := makeManagedRoot(t)
	if err := os.WriteFile(filepath.Join(root, ".envrc"), []byte("export OLD=1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runner := &fakeCommandRunner{paths: map[string]bool{"direnv": true}}
	printer := &ui.UI{In: strings.NewReader("y\n"), Out: ioDiscard{}, Err: ioDiscard{}, Interactive: true}

	err := setauth.Run(context.Background(), runner, printer, setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".envrc"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "OLD") {
		t.Fatalf(".envrc was not overwritten: %q", string(data))
	}
}

func TestRunInstallsDirenvOnMacOSWhenAccepted(t *testing.T) {
	root := makeManagedRoot(t)
	runner := &fakeCommandRunner{goos: "darwin"}
	printer := &ui.UI{In: strings.NewReader("\n"), Out: ioDiscard{}, Err: ioDiscard{}, Interactive: true}

	err := setauth.Run(context.Background(), runner, printer, setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !runner.hasCall("brew install direnv") {
		t.Fatalf("calls = %#v, missing brew install", runner.calls)
	}
}

func TestRunErrorsWhenDirenvMissingOnLinux(t *testing.T) {
	root := makeManagedRoot(t)
	runner := &fakeCommandRunner{goos: "linux"}
	err := setauth.Run(context.Background(), runner, quietUI(), setauth.Options{
		CWD:  root,
		User: "pedromvgomes",
	})
	if err == nil {
		t.Fatal("Run() succeeded, want error")
	}
	if !strings.Contains(err.Error(), "direnv.net") {
		t.Fatalf("Run() error = %v, want installation URL", err)
	}
}

type setauthResult struct {
	stdout string
	stderr string
	exit   int
	err    error
}

type fakeCommandRunner struct {
	calls     [][]string
	paths     map[string]bool
	responses map[string]setauthResult
	env       map[string]string
	goos      string
}

func (f *fakeCommandRunner) LookPath(file string) (string, error) {
	if f.paths[file] {
		return "/usr/bin/" + file, nil
	}
	return "", errors.New("not found")
}

func (f *fakeCommandRunner) Run(_ context.Context, _ string, name string, args ...string) (setauth.Result, error) {
	call := append([]string{name}, args...)
	f.calls = append(f.calls, call)
	key := strings.Join(call, " ")
	if result, ok := f.responses[key]; ok {
		return setauth.Result{Stdout: result.stdout, Stderr: result.stderr, Exit: result.exit}, result.err
	}
	return setauth.Result{}, nil
}

func (f *fakeCommandRunner) Env(name string) string {
	return f.env[name]
}

func (f *fakeCommandRunner) GOOS() string {
	if f.goos != "" {
		return f.goos
	}
	return "linux"
}

func (f *fakeCommandRunner) hasCall(want string) bool {
	for _, call := range f.calls {
		if strings.Join(call, " ") == want {
			return true
		}
	}
	return false
}
